project:
  type: book

book:
  title: "Large Language Model Policy and Practice"
  subtitle: "A framework for large language models in an Academic Medical Center"
  author: "Sean Davis"
  date: "2023-05-13"
  site-url: https://seandavi.github.io/campus-llm-kb/
  repo-url: https://github.com/seandavi/campus-llm-kb/
  repo-branch: main
  repo-actions: [edit]
  sharing: [twitter, facebook, linkedin]
  downloads: [pdf, epub]

  chapters:
    - preface.qmd
    - index.qmd
    - values.qmd
    - part: "Implementation"
      chapters:
        - framework.qmd
        - implementation.qmd
        - barriers.qmd
    - part: domainresource.qmd
      chapters:
        - resources_clinical.qmd
        - resources_research.qmd
        - resources_education.qmd
        - resources_business.qmd

    - part: "Workstream Resources"
      chapters:
        - infrastructure.qmd
        - workforce.qmd
        - ethics.qmd
        - data.qmd
        - pm_and_support.qmd
    - references.qmd
  appendices:
    - appendices.qmd
    - bill_of_rights.qmd



bibliography: references.bib

format:
  html:
    theme: cosmo
    code-link: true
  pdf:
    documentclass: scrreprt
    include-in-header: 
      text: |
        \usepackage{makeidx}
        \makeindex
    include-after-body: 
      text: |
        \printindex
  epub:
    rights: "all rights reserved"
