project:
  type: book

book:
  title: "Large Language Model Policy and Practice"
  subtitle: "A framework for large language models in an Academic Medical Center"
  author: "Sean Davis"
  date: "`r Sys.Date()`"
  downloads: [pdf, epub]

  chapters:
    - index.qmd
    - part: "Implementation"
      chapters:
        - framework.qmd
    - part: domain_resources.qmd
      chapters:
        - guiding_principles.qmd

    - part: "Workstream Resources"
      chapters:
        - bill_of_rights.qmd

    - intro.qmd
    - policy.qmd
    - implementation.qmd
    - references.qmd
    - appendices.qmd


bibliography: references.bib

format:
  html:
    theme:
      dark: darkly
      light: flatly
  pdf:
    documentclass: scrreprt
    include-in-header: 
      text: |
        \usepackage{makeidx}
        \makeindex
    include-after-body: 
      text: |
        \printindex
  epub:
    rights: "all rights reserved"
