project:
  type: book

book:
  title: "Large Language Model Policy and Practice"
  subtitle: "A framework for large language models in an Academic Medical Center"
  author: "Sean Davis"
  date: "Sys.Date()"
  downloads: [pdf, epub]
  chapters:
    - index.qmd
    - intro.qmd
    - guiding_principles.qmd
    - policy.qmd
    - references.qmd
    - appendices.qmd

bibliography: references.bib

format:
  html:
    theme:
      dark: darkly
      light: flatly
  pdf:
    documentclass: scrreprt
    include-in-header: 
      text: |
        \usepackage{makeidx}
        \makeindex
    include-after-body: 
      text: |
        \printindex
  epub:
    cover-image: cover.png
