<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>10&nbsp; Regulatory and Policy Landscape – Implementing AI in Academic Medicine</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./agentic_safety.html" rel="next">
<link href="./resources_business.html" rel="prev">
<script src="site_libs/cookie-consent/cookie-consent.js"></script>
<link href="site_libs/cookie-consent/cookie-consent.css" rel="stylesheet">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-36b256307b08637209409b134501aa37.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-KHM6W9PRES"></script>

<script type="text/plain" cookie-consent="tracking">

window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-KHM6W9PRES', { 'anonymize_ip': true});
</script>

<script type="text/javascript" charset="UTF-8">
document.addEventListener('DOMContentLoaded', function () {
cookieconsent.run({
  "notice_banner_type":"simple",
  "consent_type":"express",
  "palette":"light",
  "language":"en",
  "page_load_consent_levels":["strictly-necessary"],
  "notice_banner_reject_button_hide":false,
  "preferences_center_close_button_hide":false,
  "website_name":""
  ,
"language":"en"
  });
});
</script> 
  
<style>html{ scroll-behavior: smooth; }</style>
<script src="site_libs/quarto-diagram/mermaid.min.js"></script>
<script src="site_libs/quarto-diagram/mermaid-init.js"></script>
<link href="site_libs/quarto-diagram/mermaid.css" rel="stylesheet">


</head>

<body class="nav-sidebar floating nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Implementing AI in Academic Medicine</span>
    </a>
  </div>
        <div class="quarto-navbar-tools tools-wide tools-end">
    <a href="https://github.com/seandavi/amc-ai-governance/" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
    <div class="dropdown">
      <a href="" title="Download" id="quarto-navigation-tool-dropdown-0" class="quarto-navigation-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false" role="link" aria-label="Download"><i class="bi bi-download"></i></a>
      <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="quarto-navigation-tool-dropdown-0">
          <li>
            <a class="dropdown-item quarto-navbar-tools-item" href="./Implementing-AI-in-Academic-Medicine.pdf">
              <i class="bi bi-file-pdf pe-1"></i>
            Download PDF
            </a>
          </li>
          <li>
            <a class="dropdown-item quarto-navbar-tools-item" href="./Implementing-AI-in-Academic-Medicine.epub">
              <i class="bi bi-journal pe-1"></i>
            Download ePub
            </a>
          </li>
      </ul>
    </div>
    <div class="dropdown">
      <a href="" title="Share" id="quarto-navigation-tool-dropdown-1" class="quarto-navigation-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false" role="link" aria-label="Share"><i class="bi bi-share"></i></a>
      <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="quarto-navigation-tool-dropdown-1">
          <li>
            <a class="dropdown-item quarto-navbar-tools-item" href="https://twitter.com/intent/tweet?url=|url|">
              <i class="bi bi-twitter pe-1"></i>
            Twitter
            </a>
          </li>
          <li>
            <a class="dropdown-item quarto-navbar-tools-item" href="https://www.facebook.com/sharer/sharer.php?u=|url|">
              <i class="bi bi-facebook pe-1"></i>
            Facebook
            </a>
          </li>
          <li>
            <a class="dropdown-item quarto-navbar-tools-item" href="https://www.linkedin.com/sharing/share-offsite/?url=|url|">
              <i class="bi bi-linkedin pe-1"></i>
            LinkedIn
            </a>
          </li>
      </ul>
    </div>
</div>
          <div id="quarto-search" class="" title="Search"></div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./domainresource.html">Domain Resources</a></li><li class="breadcrumb-item"><a href="./regulatory_landscape.html"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Regulatory and Policy Landscape</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./overview.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Overview</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./values.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Values and Principles</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Implementation</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./framework.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">The Framework</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./implementation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Domain Implementation Guide</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./barriers.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Barriers and How to Address Them</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./domainresource.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Domain Resources</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./resources_clinical.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Clinical Domain</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./resources_research.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Research Domain</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./resources_education.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Education Domain</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./resources_business.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Business Operations</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./regulatory_landscape.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Regulatory and Policy Landscape</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Agentic AI in Practice</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./agentic_safety.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Agentic Safety and Guardrails</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./patient_trust.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Patient and Community Trust</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./professional_wellness.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Professional Wellness and Reducing Cognitive Burden</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Workstream Resources</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./infrastructure.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">IT Infrastructure and Security</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./workforce.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Training and Workforce Development</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ethics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Ethics, Equity, and Institutional Accountability</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Data Access and Governance</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./pm_and_support.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Project Management and AI Portfolio Governance</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./evaluation_monitoring.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Evaluation and Monitoring</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendices.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">AI Principles Across Governance Frameworks</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./bill_of_rights.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">OSTP Blueprint for an AI Bill of Rights</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./HHS.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">ONC HTI-1: Algorithm Transparency and Interoperability</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendix_workflow.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">D</span>&nbsp; <span class="chapter-title">How This Book Was Written: A Multi-Model AI Authorship Workflow</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#the-federal-regulatory-baseline" id="toc-the-federal-regulatory-baseline" class="nav-link active" data-scroll-target="#the-federal-regulatory-baseline"><span class="header-section-number">10.1</span> The Federal Regulatory Baseline</a></li>
  <li><a href="#the-executive-pivot-federal-deregulation-and-state-divergence" id="toc-the-executive-pivot-federal-deregulation-and-state-divergence" class="nav-link" data-scroll-target="#the-executive-pivot-federal-deregulation-and-state-divergence"><span class="header-section-number">10.2</span> The Executive Pivot: Federal Deregulation and State Divergence</a></li>
  <li><a href="#the-state-legislative-wave" id="toc-the-state-legislative-wave" class="nav-link" data-scroll-target="#the-state-legislative-wave"><span class="header-section-number">10.3</span> The State Legislative Wave</a></li>
  <li><a href="#professional-sovereignty-and-accreditation-standards" id="toc-professional-sovereignty-and-accreditation-standards" class="nav-link" data-scroll-target="#professional-sovereignty-and-accreditation-standards"><span class="header-section-number">10.4</span> Professional Sovereignty and Accreditation Standards</a></li>
  <li><a href="#international-requirements-for-global-research-partners" id="toc-international-requirements-for-global-research-partners" class="nav-link" data-scroll-target="#international-requirements-for-global-research-partners"><span class="header-section-number">10.5</span> International Requirements for Global Research Partners</a></li>
  <li><a href="#sec-regulatory-start" id="toc-sec-regulatory-start" class="nav-link" data-scroll-target="#sec-regulatory-start"><span class="header-section-number">10.6</span> Where to Start</a>
  <ul class="collapse">
  <li><a href="#starter-project-1-ai-regulatory-compliance-mapping" id="toc-starter-project-1-ai-regulatory-compliance-mapping" class="nav-link" data-scroll-target="#starter-project-1-ai-regulatory-compliance-mapping"><span class="header-section-number">10.6.1</span> Starter Project 1: AI Regulatory Compliance Mapping</a></li>
  <li><a href="#starter-project-2-annual-ai-governance-report-to-the-board" id="toc-starter-project-2-annual-ai-governance-report-to-the-board" class="nav-link" data-scroll-target="#starter-project-2-annual-ai-governance-report-to-the-board"><span class="header-section-number">10.6.2</span> Starter Project 2: Annual AI Governance Report to the Board</a></li>
  </ul></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/seandavi/amc-ai-governance/edit/main/regulatory_landscape.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./domainresource.html">Domain Resources</a></li><li class="breadcrumb-item"><a href="./regulatory_landscape.html"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Regulatory and Policy Landscape</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span id="sec-regulatory" class="quarto-section-identifier"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Regulatory and Policy Landscape</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>An AMC operating in 2026 does not face a single AI regulatory framework. It faces a patchwork of federal transparency mandates, state disclosure and anti-discrimination laws, professional society standards, and international requirements for any institution with global research partnerships, each with its own effective date, its own enforcement mechanism, and its own definition of which AI tools it covers. The temptation is to treat this as a compliance problem: assemble a checklist, check each box, and move on.</p>
<p>That approach fails, and the eighteen months before this chapter was last revised show why. Colorado enacted what was widely described as the most demanding state AI law in the country, then watched a federal court stay its enforcement in April 2026 and the legislature repeal it in May, six weeks before it was to take effect. The European Union deferred the high-risk obligations of its AI Act by sixteen months for one class of systems and by two years for the class that actually contains medical devices. A compliance matrix built in early 2025 would now be wrong in more rows than it is right.</p>
<p>The more durable approach is to treat AI governance as a risk management function that responds to a shifting grid rather than a fixed list. This chapter gives AMC legal, compliance, and informatics leaders the state of that grid as of August 2026, with emphasis on the provisions that most directly affect clinical and research operations. Dates are given as they stand at the time of writing. Readers should assume that at least one of them has moved and should confirm anything load-bearing against the primary source before relying on it.</p>
<section id="the-federal-regulatory-baseline" class="level2" data-number="10.1">
<h2 data-number="10.1" class="anchored" data-anchor-id="the-federal-regulatory-baseline"><span class="header-section-number">10.1</span> The Federal Regulatory Baseline</h2>
<p>The foundational federal regulatory layer consists of rules from four agencies: <a href="https://www.healthit.gov">ONC</a>, FDA, CMS, and HHS OCR. Each has moved from guidance to enforcement-capable rule since 2024.</p>
<p>The ONC HTI-1 rule, published January 2024 with the certification compliance deadline falling at the end of that year, is the most operationally significant for clinical informatics teams <span class="citation" data-cites="ONC2024-hti1">(<a href="references.html#ref-ONC2024-hti1" role="doc-biblioref">Office of the National Coordinator for Health Information Technology 2024</a>)</span>. It creates a new regulatory category, Decision Support Interventions, and divides it in two. Evidence-based DSI, the larger and more familiar group, covers order sets, alerts, and reference material, and carries a shorter disclosure list. Predictive DSI, which covers EHR-based algorithms that generate patient-specific output from a statistical or machine-learned model, carries a longer one. For each qualifying predictive tool, certified EHR vendors must make accessible a structured set of source attributes that includes training data sources, performance characteristics on the populations the tool was validated in, known limitations, and update history. The rule does not require AMCs to build new infrastructure. It requires AMCs to demand that their EHR vendors fulfill their existing compliance obligations, and to incorporate the provided source attributes into their ongoing governance processes.</p>
<p>The FDA’s Predetermined Change Control Plan guidance, finalized December 2024, provides the regulatory pathway for adaptive AI medical devices — systems that update their parameters based on new data after initial clearance or approval <span class="citation" data-cites="FDA2024-pccp">(<a href="references.html#ref-FDA2024-pccp" role="doc-biblioref">U.S. Food and Drug Administration 2024</a>)</span>. Traditional device regulation assumes a static design; a device that functions differently after deployment requires a new submission. The PCCP pathway allows a developer to specify in advance the types and bounds of permitted changes, the performance criteria that must be met before changes are implemented, and the monitoring required to detect unintended effects. AMCs that have developed or licensed AI-enabled SaMD (Software as a Medical Device) and intend to update those tools over time should assess whether a PCCP is the appropriate regulatory pathway.</p>
<p>HHS OCR’s Section 1557 final rule was published in May 2024 and became effective in July of that year, but the provision that matters most here carried its own later deadline <span class="citation" data-cites="HHS2024-1557">(<a href="references.html#ref-HHS2024-1557" role="doc-biblioref">U.S. Department of Health and Human Services, Office for Civil Rights 2024</a>)</span>. Section 92.210, which covers patient care decision support tools, had a compliance date of May 1, 2025. Covered entities, which include most AMCs, may not use patient care decision support tools that result in discriminatory treatment based on race, color, national origin, sex, age, or disability. The rule does not define which algorithms are covered with surgical precision. It requires covered entities to make reasonable efforts to identify the tools they use that employ those characteristics as input variables, and to mitigate the risk of discrimination those tools present. OCR has not issued implementing guidance, which leaves each institution to decide what a reasonable effort looks like. In practice, an institution that cannot produce a written record of which tools it examined and what it found will have a hard time demonstrating that it made one.</p>
<p>Medicare Advantage rules address a narrower but important point: an algorithm may assist a coverage determination, but it may not be the thing that makes it. The requirement does not originate in a rule about AI. It lives in 42 CFR 422.101(c), which obliges Medicare Advantage organizations to base medical necessity determinations on the individual patient’s circumstances <span class="citation" data-cites="CFR422101">(<a href="references.html#ref-CFR422101" role="doc-biblioref">Office of the Federal Register 2026</a>)</span>. CMS applied that provision to AI directly in a February 2024 memorandum, stating that an algorithm which determines coverage from a larger data set rather than from the individual patient’s medical history, the treating physician’s recommendations, and the clinical notes would not comply <span class="citation" data-cites="CMS2024-mafaq">(<a href="references.html#ref-CMS2024-mafaq" role="doc-biblioref">Centers for Medicare and Medicaid Services 2024</a>)</span>. The same memorandum reminded plans that algorithmic tools can exacerbate discrimination and bias, and that Section 1557 reaches them.</p>
<p>Whether any of the device rules apply at all turns on a threshold question that AMCs building their own tools routinely get wrong. Section 3060(a) of the 21st Century Cures Act added section 520(o)(1)(E) to the Food, Drug, and Cosmetic Act, excluding clinical decision support software from the device definition when it satisfies four criteria. FDA reissued its interpretation of those criteria in January 2026, superseding the 2022 guidance that most institutional policies were written against <span class="citation" data-cites="FDA2026-cds">(<a href="references.html#ref-FDA2026-cds" role="doc-biblioref">U.S. Food and Drug Administration 2026</a>)</span>. One change is worth knowing. Software that returns a single recommendation, rather than a set of options, had been read as failing the third criterion and therefore as a device. FDA now says it intends to exercise enforcement discretion for such functions where only one option is clinically appropriate and every other criterion is met. <a href="#fig-cds-decision-tree" class="quarto-xref">Figure&nbsp;<span>10.1</span></a> walks the four criteria in the order the statute sets them out.</p>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div id="fig-cds-decision-tree" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-cds-decision-tree-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div>
<pre class="mermaid mermaid-js" data-label="fig-cds-decision-tree">flowchart TD
    A([Software function intended to\nsupport a clinical decision]) --&gt; B{"Criterion 1: Does it acquire, process,\nor analyze a medical image, an IVD\nsignal, or a pattern or signal from a\nsignal acquisition system?"}
    B --&gt;|Yes| Z[Device software function:\nFDA oversight applies]
    B --&gt;|No| C{"Criterion 2: Is it intended to display,\nanalyze, or print medical information\nabout a patient, or other medical\ninformation such as guidelines?"}
    C --&gt;|No| Z
    C --&gt;|Yes| D{"Criterion 3: Is it intended to support\nor provide recommendations to a health\ncare professional about prevention,\ndiagnosis, or treatment?"}
    D --&gt;|No — patient-facing or\nnot recommendation-shaped| Z
    D --&gt;|Yes| E{"Criterion 4: Is it intended to let that\nprofessional independently review the\nbasis for the recommendation, so that\nprimary reliance on it is not the intent?"}
    E --&gt;|No — basis not reviewable| Z
    E --&gt;|Yes| Y[Non-device CDS:\noutside the device definition]
</pre>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-cds-decision-tree-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;10.1: The four Non-Device CDS criteria at section 520(o)(1)(E) of the Food, Drug, and Cosmetic Act, as interpreted by FDA’s January 2026 guidance. A software function must satisfy all four to fall outside the device definition. Failing any one of them makes it a device software function.
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="the-executive-pivot-federal-deregulation-and-state-divergence" class="level2" data-number="10.2">
<h2 data-number="10.2" class="anchored" data-anchor-id="the-executive-pivot-federal-deregulation-and-state-divergence"><span class="header-section-number">10.2</span> The Executive Pivot: Federal Deregulation and State Divergence</h2>
<p>The Biden administration’s Executive Order 14110, signed October 30, 2023, directed federal agencies to develop AI risk assessments, transparency requirements, and accountability frameworks for government AI use, and signaled an expansive federal regulatory posture <span class="citation" data-cites="EO14110">(<a href="references.html#ref-EO14110" role="doc-biblioref">Executive Office of the President 2023</a>)</span>. The Trump administration revoked it on January 23, 2025, replacing it with Executive Order 14179, which directs agencies to identify and remove policies that act as barriers to AI development <span class="citation" data-cites="EO14179">(<a href="references.html#ref-EO14179" role="doc-biblioref">Executive Office of the President 2025b</a>)</span>.</p>
<p>The posture hardened from there. Executive Order 14365, issued December 16, 2025, directs the Attorney General to stand up an AI Litigation Task Force whose sole charge is to challenge state AI laws, and directs the Department of Commerce to identify state laws for referral to it <span class="citation" data-cites="EO14365">(<a href="references.html#ref-EO14365" role="doc-biblioref">Executive Office of the President 2025a</a>)</span>. That is not a statement of intent that stayed on paper. When xAI sued to enjoin the Colorado AI Act in April 2026, the United States moved to intervene against the state within two weeks <span class="citation" data-cites="XAI2026-weiser">(<a href="references.html#ref-XAI2026-weiser" role="doc-biblioref">U.S. District Court for the District of Colorado 2026</a>)</span>.</p>
<p>For AMCs, the practical implication is a division between what has been made and what is being unmade. The rules already in effect, including ONC HTI-1, the FDA device pathway, and Section 1557, remain law; a revoked executive order does not repeal a promulgated regulation, and none of these requires fresh executive guidance to enforce. What has changed is the direction of travel at the federal level and, more consequentially for a multi-state health system, the durability of the state laws that were expected to set the practical ceiling. Colorado and California have enacted, and other states are considering, AI transparency and accountability requirements that go beyond the federal floor. Those requirements are now themselves contested, which makes the compliance question harder rather than easier: an AMC cannot safely build to the most demanding state standard if that standard may be enjoined, nor safely ignore it if it may not.</p>
</section>
<section id="the-state-legislative-wave" class="level2" data-number="10.3">
<h2 data-number="10.3" class="anchored" data-anchor-id="the-state-legislative-wave"><span class="header-section-number">10.3</span> The State Legislative Wave</h2>
<p>Colorado Senate Bill 24-205, the Colorado Artificial Intelligence Act, was for two years the reference point for state AI regulation in the United States. It covered “high-risk AI systems” used in consequential decisions, a category that included healthcare. It required deployers, meaning the entities that put the tools to use rather than the developers who built them, to run a risk management program, conduct and document impact assessments, give consumers notice of AI use in consequential decisions, and use reasonable care to prevent algorithmic discrimination <span class="citation" data-cites="ColoradoSB24205">(<a href="references.html#ref-ColoradoSB24205" role="doc-biblioref"><span>SB 24-205</span> 2024</a>)</span>. Many institutions, this book’s earlier draft included, built their planning around a June 30, 2026 effective date.</p>
<p>That date was itself a retreat. The Act was originally to take effect February 1, 2026, and the legislature moved it to June 30 in an August 2025 special session, which is the first sign that the compliance regime it described was harder to stand up than it had looked on passage <span class="citation" data-cites="ColoradoSB25B004">(<a href="references.html#ref-ColoradoSB25B004" role="doc-biblioref"><span>SB 25B-004</span> 2025</a>)</span>.</p>
<p>None of it took effect. xAI sued Colorado’s attorney general in April 2026 on First Amendment, Commerce Clause, and due process grounds; the United States moved to intervene on the same side; and on April 27, 2026 a magistrate judge granted a joint motion staying enforcement while the preliminary injunction motion was briefed <span class="citation" data-cites="XAI2026-weiser">(<a href="references.html#ref-XAI2026-weiser" role="doc-biblioref">U.S. District Court for the District of Colorado 2026</a>)</span>. Two and a half weeks later the legislature made the litigation moot. Senate Bill 26-189, signed May 14, 2026, repealed the Colorado AI Act and reenacted it as a considerably narrower statute governing “automated decision-making technology” that materially influences a consequential decision <span class="citation" data-cites="ColoradoSB26189">(<a href="references.html#ref-ColoradoSB26189" role="doc-biblioref"><span>SB 26-189</span> 2026</a>)</span>. Health-care services remain on the enumerated list of consequential decisions, alongside education, employment, housing, financial and lending services, insurance, and essential government services, and the duties attach to any deployer rather than only to payers. An AMC using an automated system that materially influences a patient’s access to or eligibility for care is therefore covered as a provider, not merely as a plan operator.</p>
<p>What survives matters as much as what does not. The new statute drops the three obligations that made the original demanding: the risk management program, the impact assessment, and the duty of reasonable care to prevent algorithmic discrimination. In their place it puts a disclosure-and-rights framework. Deployers must tell a person when they are interacting with an automated system, explain an adverse outcome in plain language within thirty days, correct inaccurate personal data on request, and provide meaningful human review and reconsideration. Developers must give deployers technical documentation covering intended uses, categories of training data, known limitations, and instructions for appropriate use. Both sides must retain compliance records for at least three years, and enforcement runs through the Colorado Consumer Protection Act. The documentation obligation and the attorney general’s rulemaking both begin January 1, 2027.</p>
<p>For an AMC, the practical effect is that a governance program built to the old Colorado standard is now over-built for Colorado and under-built for nothing in particular. That is not an argument for dismantling it. Impact assessments and bias auditing remain the way an institution answers the Section 1557 question, and Section 1557 has not moved. But an institution that justified those activities to its board solely as Colorado compliance should expect to be asked why it is still doing them, and should have a better answer ready.</p>
<p>Colorado also did something narrower and more durable in the same session, and it is the part an AMC that operates a health plan should read first. House Bill 26-1139, signed June 2, 2026 and effective January 1, 2027, governs AI used in utilization review by health insurers, pharmacy benefit managers, utilization review organizations, and managed care entities <span class="citation" data-cites="ColoradoHB26-1139">(<a href="references.html#ref-ColoradoHB26-1139" role="doc-biblioref"><span>HB 26-1139</span> 2026</a>)</span>. It requires such systems to rest on the patient’s medical history and individual clinical circumstances rather than on group data alone, and it bars a medical necessity denial that rests solely on AI output without review by a licensed clinician. Regulated entities must disclose their AI utilization review functions to state agencies and retain audit information demonstrating compliance. The structure will look familiar: it is the Medicare Advantage requirement at 42 CFR 422.101(c), generalized beyond Medicare Advantage and given a documentation duty and an audit trail. An AMC that runs a provider-sponsored plan in Colorado now faces both.</p>
<p>California’s posture is more fragmented but cumulatively significant. AB 3030, effective January 2025, requires disclosure on AI-generated patient communications, though it exempts communications read and reviewed by a licensed provider <span class="citation" data-cites="CalAB3030-2024">(<a href="references.html#ref-CalAB3030-2024" role="doc-biblioref"><span>AB 3030</span> 2024</a>)</span>. New York City’s Local Law 144 requires independent bias audits for AI-assisted hiring decisions, a provision relevant to AMCs using algorithmic screening, with the caveat that it reaches only positions located within New York City <span class="citation" data-cites="NYCLL144">(<a href="references.html#ref-NYCLL144" role="doc-biblioref">Local Law 144 2021</a>)</span>.</p>
<p>Enforcement in this area has come more from state attorneys general than from the Federal Trade Commission, and AMCs should read the FTC’s 2024 activity carefully rather than by its name. Operation AI Comply, announced September 25, 2024, named five respondents: DoNotPay over “robot lawyer” claims, Rytr over a tool for mass-producing fake reviews, and Ascend Ecom, Ecommerce Empire Builders, and FBA Machine over AI-branded e-commerce income schemes <span class="citation" data-cites="FTC2024-operationai">(<a href="references.html#ref-FTC2024-operationai" role="doc-biblioref">Federal Trade Commission 2024</a>)</span>. No health care company was among them, and nothing in the sweep addressed clinical tools. The health care AI enforcement action of that period came a week earlier from Texas, where the attorney general settled with Pieces Technologies, a clinical summarization vendor whose products were in use at four Texas hospitals, over representations about the accuracy and hallucination rate of its generative AI <span class="citation" data-cites="TexasAG2024-pieces">(<a href="references.html#ref-TexasAG2024-pieces" role="doc-biblioref">Office of the Attorney General of Texas 2024</a>)</span>. The settlement imposed no penalty but did impose disclosure and documentation obligations. It is the more instructive precedent for AMCs, and not because of what it did to the vendor. The claims at issue were performance claims of exactly the kind that appear in a procurement deck, and an AMC that accepts them without independent verification is relying on a representation a state regulator has already found deceptive.</p>
<p>The compliance challenge for national AMCs is that these laws have different definitions of covered AI, different disclosure requirements, and different enforcement mechanisms, and that the most demanding of them is now the least stable. Adopting the strictest applicable standard as a uniform default is still the right instinct, because it avoids maintaining state-specific workflows. It is a weaker guarantee than it was, because the strictest standard may not survive the year.</p>
<div id="tbl-regulatory-timeline" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-regulatory-timeline-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;10.1: Key regulatory milestones for AMC AI governance, current as of August 2026 <span class="citation" data-cites="ONC2024-hti1 FDA2024-pccp FDA2026-cds HHS2024-1557 CFR422101 CMS2024-mafaq ColoradoSB24205 ColoradoSB25B004 ColoradoSB26189 ColoradoHB26-1139 CalAB3030-2024 EUAI2024 EUOmnibus2026">(<a href="references.html#ref-ONC2024-hti1" role="doc-biblioref">Office of the National Coordinator for Health Information Technology 2024</a>; <a href="references.html#ref-FDA2024-pccp" role="doc-biblioref">U.S. Food and Drug Administration 2024</a>, <a href="references.html#ref-FDA2026-cds" role="doc-biblioref">2026</a>; <a href="references.html#ref-HHS2024-1557" role="doc-biblioref">U.S. Department of Health and Human Services, Office for Civil Rights 2024</a>; <a href="references.html#ref-CFR422101" role="doc-biblioref">Office of the Federal Register 2026</a>; <a href="references.html#ref-CMS2024-mafaq" role="doc-biblioref">Centers for Medicare and Medicaid Services 2024</a>; <a href="references.html#ref-ColoradoSB24205" role="doc-biblioref"><span>SB 24-205</span> 2024</a>, <a href="references.html#ref-ColoradoSB25B004" role="doc-biblioref"><span>SB 25B-004</span> 2025</a>, <a href="references.html#ref-ColoradoSB26189" role="doc-biblioref"><span>SB 26-189</span> 2026</a>, <a href="references.html#ref-ColoradoHB26-1139" role="doc-biblioref"><span>HB 26-1139</span> 2026</a>, <a href="references.html#ref-CalAB3030-2024" role="doc-biblioref"><span>AB 3030</span> 2024</a>, <a href="references.html#ref-EUAI2024" role="doc-biblioref">Regulation (<span>EU</span>) 2024/1689 of the European Parliament and of the Council on Artificial Intelligence (Artificial Intelligence Act) 2024</a>, <a href="references.html#ref-EUOmnibus2026" role="doc-biblioref">Regulation (<span>EU</span>) 2026/1744 of the European Parliament and of the Council of 8 July 2026 Amending Regulations (<span>EU</span>) 2024/1689, (<span>EU</span>) 2018/1139 and (<span>EU</span>) 2023/1230 as Regards the Simplification of the Implementation of Harmonised Rules on Artificial Intelligence (Digital Omnibus on <span>AI</span>) 2026</a>)</span>
</figcaption>
<div aria-describedby="tbl-regulatory-timeline-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 19%">
<col style="width: 15%">
<col style="width: 33%">
<col style="width: 31%">
</colgroup>
<thead>
<tr class="header">
<th>Agency / Body</th>
<th>Rule / Law</th>
<th>Status as of August 2026</th>
<th>Key Provision for AMCs</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>ONC</td>
<td>HTI-1 Algorithm Transparency</td>
<td>In effect; certification deadline December 2024</td>
<td>EHR vendors must surface DSI source attributes within clinical workflow</td>
</tr>
<tr class="even">
<td>FDA</td>
<td>PCCP Guidance</td>
<td>Final, December 2024</td>
<td>Adaptive AI-SaMD may update within pre-specified bounds without new filing</td>
</tr>
<tr class="odd">
<td>FDA</td>
<td>Clinical Decision Support Software Guidance</td>
<td>Final, reissued January 2026</td>
<td>Four criteria determine whether a CDS tool is a regulated device</td>
</tr>
<tr class="even">
<td>HHS OCR</td>
<td>Section 1557 Final Rule</td>
<td>In effect; §92.210 compliance date May 1, 2025</td>
<td>Covered entities may not use discriminatory patient care decision-support tools</td>
</tr>
<tr class="odd">
<td>CMS</td>
<td>42 CFR 422.101(c), applied to AI by February 2024 memorandum</td>
<td>In effect</td>
<td>Coverage determinations must rest on the individual patient’s circumstances, not on an algorithm alone</td>
</tr>
<tr class="even">
<td>Colorado</td>
<td>SB 24-205 (CAIA)</td>
<td>Repealed May 14, 2026; start date deferred to June 30, 2026 by SB 25B-004; enforcement stayed April 27, 2026; never took effect</td>
<td>Superseded; see SB 26-189</td>
</tr>
<tr class="odd">
<td>Colorado</td>
<td>SB 26-189 (ADMT)</td>
<td>Enacted; documentation duties and AG rulemaking begin January 1, 2027</td>
<td>Notice of automated decisions, plain-language explanation of adverse outcomes, human review, three-year records</td>
</tr>
<tr class="even">
<td>Colorado</td>
<td>HB 26-1139</td>
<td>Signed June 2, 2026; effective January 1, 2027</td>
<td>AI in utilization review must rest on individual clinical circumstances; no medical necessity denial on AI output alone; disclosure and audit records</td>
</tr>
<tr class="odd">
<td>California</td>
<td>AB 3030</td>
<td>In effect since January 2025</td>
<td>Disclosure on AI-generated patient communications, unless reviewed by a licensed provider</td>
</tr>
<tr class="even">
<td>EU</td>
<td>AI Act, Annex III high-risk systems</td>
<td>Deferred to December 2, 2027</td>
<td>Conformity assessment, technical documentation, human oversight, database registration</td>
</tr>
<tr class="odd">
<td>EU</td>
<td>AI Act, Annex I high-risk systems (includes regulated medical devices)</td>
<td>Deferred to August 2, 2028</td>
<td>Same obligations, applied through existing product legislation</td>
</tr>
<tr class="even">
<td>EU</td>
<td>AI Act, Article 50 transparency duties</td>
<td>Unchanged; apply from August 2, 2026</td>
<td>Disclosure that a user is interacting with an AI system; labelling of synthetic content</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</section>
<section id="professional-sovereignty-and-accreditation-standards" class="level2" data-number="10.4">
<h2 data-number="10.4" class="anchored" data-anchor-id="professional-sovereignty-and-accreditation-standards"><span class="header-section-number">10.4</span> Professional Sovereignty and Accreditation Standards</h2>
<p>Alongside the legislative layer, professional societies and accreditation bodies have moved to codify AI governance expectations in standards that carry their own enforcement mechanisms — credentialing, accreditation, and membership. For AMCs, these standards often have more immediate operational effect than distant federal rules, because their consequences for day-to-day operations are more direct.</p>
<p>The <a href="https://www.nist.gov/itl/ai-risk-management-framework">NIST AI Risk Management Framework</a> supplies the organizational scaffold that most U.S. health systems have adopted for institutional AI governance <span class="citation" data-cites="NIST2023-airm">(<a href="references.html#ref-NIST2023-airm" role="doc-biblioref">National Institute of Standards and Technology 2023</a>)</span>. Its four functions, Govern, Map, Measure, and Manage, give AI program design a structure that maps onto committee charters and reporting lines without much translation. That is the main reason it spread: it is a vocabulary an institution can adopt without first agreeing on a definition of AI. The companion Generative AI Profile extends the framework to risks specific to large language models, naming confabulation, training-data memorization under data privacy, and harmful bias and homogenization, none of which the original framework fully anticipated <span class="citation" data-cites="NIST2024-gen600">(<a href="references.html#ref-NIST2024-gen600" role="doc-biblioref">National Institute of Standards and Technology 2024</a>)</span>.</p>
<p>The AMA’s November 2024 policy on augmented intelligence is the clearest professional-society statement of where accountability sits <span class="citation" data-cites="AMA2024-ai-principles">(<a href="references.html#ref-AMA2024-ai-principles" role="doc-biblioref">American Medical Association 2024</a>)</span>. It holds that clinical decisions influenced by AI must include specified qualified human intervention points, and defines a qualified human as a physician able to provide the same service independently, without the aid of AI. It also holds that physicians should receive enough detail about how a tool was trained and validated to judge whether it reasonably applies to the patient in front of them, and that transparency and explainability in design and development should be mandated by law where feasible. The practical significance is in the framing: the physician remains the final arbiter of clinical decisions and bears professional accountability for actions taken with or without AI input. This is not merely an ethical position. It is the standard a plaintiff’s expert will be asked to apply, and it does not soften when the tool was validated, procured, and approved by the institution rather than chosen by the physician.</p>
<p>The ISO/IEC 42001:2023 standard for AI management systems provides a certification pathway for institutions that want to demonstrate systematic AI governance to regulators, accreditors, and payers <span class="citation" data-cites="ISO2023-42001">(<a href="references.html#ref-ISO2023-42001" role="doc-biblioref"><span>ISO/IEC 42001</span> 2023</a>)</span>. It is the closest analogue in AI to ISO 27001 for information security, a voluntary management-system standard whose value depends less on its content than on whether the parties an institution answers to have begun asking for it. Some AMCs report that vendors and payers have started to ask; that is worth confirming in your own market rather than assuming. The work is not wasted either way: the control set overlaps substantially with the NIST framework, so an institution with a mature NIST-aligned program is doing most of what certification would require already.</p>
</section>
<section id="international-requirements-for-global-research-partners" class="level2" data-number="10.5">
<h2 data-number="10.5" class="anchored" data-anchor-id="international-requirements-for-global-research-partners"><span class="header-section-number">10.5</span> International Requirements for Global Research Partners</h2>
<p>For AMCs with international research partnerships, clinical trial enrollment in Europe, or data sharing with EU-based institutions, the <a href="https://eur-lex.europa.eu/eli/reg/2024/1689/oj">EU AI Act</a> represents a material compliance obligation, though on a later schedule than the one most institutional plans were built against <span class="citation" data-cites="EUAI2024">(<a href="references.html#ref-EUAI2024" role="doc-biblioref">Regulation (<span>EU</span>) 2024/1689 of the European Parliament and of the Council on Artificial Intelligence (Artificial Intelligence Act) 2024</a>)</span>. Regulation (EU) 2026/1744, the Digital Omnibus on AI, was adopted July 8, 2026, published in the Official Journal on July 24, and entered into force on July 27 <span class="citation" data-cites="EUOmnibus2026">(<a href="references.html#ref-EUOmnibus2026" role="doc-biblioref">Regulation (<span>EU</span>) 2026/1744 of the European Parliament and of the Council of 8 July 2026 Amending Regulations (<span>EU</span>) 2024/1689, (<span>EU</span>) 2018/1139 and (<span>EU</span>) 2023/1230 as Regards the Simplification of the Implementation of Harmonised Rules on Artificial Intelligence (Digital Omnibus on <span>AI</span>) 2026</a>)</span>. It defers the high-risk obligations, and it does so unevenly. Systems falling under Article 6(2) and Annex III now become subject to those obligations on December 2, 2027. Systems falling under Annex I, which reaches AI embedded in products already regulated under EU sectoral legislation and is therefore where AI-enabled medical devices actually sit, are deferred further, to August 2, 2028. The stated rationale was that harmonised standards and national competent authorities were not ready in time.</p>
<p>Two points are worth separating out, because the chapter’s earlier framing blurred them. The first is that “clinical decision support” is not itself a named high-risk category. A clinical AI tool is high-risk under the Act when it qualifies as a medical device requiring third-party conformity assessment, which routes it through Annex I and the 2028 date, or when it falls into one of the Annex III uses, such as determining access to essential services. The second is that the deferral is not general. The Article 50 transparency duties, which require disclosing that a person is interacting with an AI system and labelling synthetic content, were not moved and apply from August 2, 2026. An AMC running a patient-facing chatbot at a European affiliate has an obligation now, not in 2027.</p>
<p>The substance of the high-risk obligations is unchanged. Such systems must undergo a conformity assessment before deployment, maintain technical documentation, implement human oversight measures, and register in the EU AI database. The practical implication for AMC research operations is that any AI tool used in a clinical study enrolling EU subjects, or any EHR-integrated AI system at an EU affiliate, must be assessed against these requirements well before the applicable date, because conformity assessment is not a task that compresses. The deferral bought institutions time; it did not remove the work. AMC general counsel should treat this as a research contracts and technology transfer issue, not solely an IT compliance matter.</p>
<p>The Brussels Effect, Anu Bradford’s term for the tendency of EU regulation to become a de facto global standard because multinational firms find it cheaper to apply the highest standard uniformly than to maintain separate product lines, is the reason this section matters to AMCs with no European operations at all <span class="citation" data-cites="Bradford2012-brussels">(<a href="references.html#ref-Bradford2012-brussels" role="doc-biblioref">Bradford 2012</a>)</span>. If a vendor builds its product to EU requirements to preserve market access there, an AMC that buys the product inherits both the documentation and the design constraints. Whether the deferral to 2027 and 2028 weakens that mechanism is an open question. A delayed standard exerts less pull than an imminent one, and the same omnibus that moved the dates was framed as simplification, which is not the direction a regulation travels when it is about to become the world’s default.</p>
</section>
<section id="sec-regulatory-start" class="level2" data-number="10.6">
<h2 data-number="10.6" class="anchored" data-anchor-id="sec-regulatory-start"><span class="header-section-number">10.6</span> Where to Start</h2>
<section id="starter-project-1-ai-regulatory-compliance-mapping" class="level3" data-number="10.6.1">
<h3 data-number="10.6.1" class="anchored" data-anchor-id="starter-project-1-ai-regulatory-compliance-mapping"><span class="header-section-number">10.6.1</span> Starter Project 1: AI Regulatory Compliance Mapping</h3>
<p><strong>What it is:</strong> A mapping of the institution’s current AI tool inventory (see <a href="resources_clinical.html#sec-clinical-start" class="quarto-xref"><span>Section 6.4</span></a>) against the applicable regulatory frameworks in <a href="#tbl-regulatory-timeline" class="quarto-xref">Table&nbsp;<span>10.1</span></a>, identifying which tools are covered by which rules and where compliance gaps exist.</p>
<p><strong>Why now:</strong> Several rules are already in effect and others arrive in 2027 and 2028. An institution that has not completed this mapping cannot certify compliance to its board, its accreditors, or its patients. The Colorado episode is also the argument for building the mapping as a living document rather than a one-time exercise: any institution that completed this project in 2025 has at least four rows that are now wrong.</p>
<p><strong>How to execute:</strong> Use the clinical AI inventory as the starting point. For each tool, determine: Does it qualify as a predictive DSI under HTI-1? Does it satisfy all four Non-Device CDS criteria, or is it a device software function? Does it materially influence a decision that qualifies as “consequential” under Colorado SB 26-189, which brings notice, explanation, and human-review duties from January 2027? Does it generate patient communications covered by California AB 3030, and if so, is it exempt because a licensed provider reads and reviews the output? Does it use race, color, national origin, sex, age, or disability as an input variable, which is the Section 1557 trigger? The output is a compliance matrix that the legal and compliance teams can use to prioritize remediation. Record the date and the source consulted for each cell, so that the next revision can tell what has changed from what merely looks unfamiliar.</p>
<p><strong>Buy vs.&nbsp;build:</strong> Legal analysis and governance work. Some commercial GRC (Governance, Risk, and Compliance) platforms have begun adding AI regulatory mapping capabilities, but the analysis itself requires legal judgment that cannot be fully automated.</p>
</section>
<section id="starter-project-2-annual-ai-governance-report-to-the-board" class="level3" data-number="10.6.2">
<h3 data-number="10.6.2" class="anchored" data-anchor-id="starter-project-2-annual-ai-governance-report-to-the-board"><span class="header-section-number">10.6.2</span> Starter Project 2: Annual AI Governance Report to the Board</h3>
<p><strong>What it is:</strong> A structured annual report to the institutional board of trustees on the state of the AI governance program — deployed tools, regulatory compliance status, adverse events, and strategic priorities.</p>
<p><strong>Why now:</strong> The legal driver that made this project easy to justify has gone away. Colorado SB 24-205 would have required documented impact assessments for high-risk AI; its replacement does not, and no other statute imposes a board reporting duty specific to AI. The case now has to be made on its own terms, and it can be. Section 1557 still requires covered entities to make reasonable efforts to identify and mitigate discrimination in patient care decision support tools, and a board-level report is the natural artifact that demonstrates those efforts were institutional rather than ad hoc. Colorado SB 26-189 still requires deployers to explain adverse automated outcomes within thirty days and to retain records for three years, which is difficult to do reliably without a maintained inventory. And an AMC that cannot say how many AI tools it is running, who approved them, and how they are performing has a governance problem regardless of what any statute requires.</p>
<p><strong>How to execute:</strong> Define a standard reporting template that includes: inventory of deployed AI tools with risk tiers, compliance status against applicable regulations, any adverse events involving AI in the reporting period, performance monitoring findings, and planned additions or retirements. Present to the board annually, with quarterly updates to the relevant board committee if the portfolio is large. The report format should be adapted from the NIST AI RMF Govern function documentation requirements.</p>


<div id="refs" class="references csl-bib-body hanging-indent" role="list" style="display: none">
<div id="ref-CalAB3030-2024" class="csl-entry" role="listitem">
<span>AB 3030</span>: Health Care: Artificial Intelligence (2024). <a href="https://leginfo.legislature.ca.gov/faces/billNavClient.xhtml?bill_id=202320240AB3030">https://leginfo.legislature.ca.gov/faces/billNavClient.xhtml?bill_id=202320240AB3030</a>.
</div>
<div id="ref-AMA2024-ai-principles" class="csl-entry" role="listitem">
American Medical Association. 2024. <em>Augmented Intelligence Development, Deployment, and Use in Health Care</em>. <a href="https://www.ama-assn.org/system/files/ama-ai-principles.pdf">https://www.ama-assn.org/system/files/ama-ai-principles.pdf</a>.
</div>
<div id="ref-Bradford2012-brussels" class="csl-entry" role="listitem">
Bradford, Anu. 2012. <span>“The <span>Brussels</span> Effect.”</span> <em>Northwestern University Law Review</em> 107 (1): 1–67. <a href="https://scholarlycommons.law.northwestern.edu/nulr/vol107/iss1/1/">https://scholarlycommons.law.northwestern.edu/nulr/vol107/iss1/1/</a>.
</div>
<div id="ref-CMS2024-mafaq" class="csl-entry" role="listitem">
Centers for Medicare and Medicaid Services. 2024. <em>Frequently Asked Questions Related to Coverage Criteria and Utilization Management Requirements in <span>CMS</span> Final Rule (<span>CMS</span>-4201-<span>F</span>)</em>. <a href="https://www.cms.gov/files/document/hpms-memo-faq-coverage-criteria-and-utilization-management-cms-4201-f-02-6-2024-pdf.pdf">https://www.cms.gov/files/document/hpms-memo-faq-coverage-criteria-and-utilization-management-cms-4201-f-02-6-2024-pdf.pdf</a>.
</div>
<div id="ref-EO14110" class="csl-entry" role="listitem">
Executive Office of the President. 2023. <span>“Safe, Secure, and Trustworthy Development and Use of Artificial Intelligence.”</span> In <em>Federal Register</em>, Executive Order 14110, vol. 88. <a href="https://www.federalregister.gov/documents/2023/11/01/2023-24283/safe-secure-and-trustworthy-development-and-use-of-artificial-intelligence">https://www.federalregister.gov/documents/2023/11/01/2023-24283/safe-secure-and-trustworthy-development-and-use-of-artificial-intelligence</a>.
</div>
<div id="ref-EO14365" class="csl-entry" role="listitem">
Executive Office of the President. 2025a. <span>“Ensuring a National Policy Framework for Artificial Intelligence.”</span> In <em>Federal Register</em>, Executive Order 14365, vol. 90. <a href="https://www.federalregister.gov/documents/2025/12/16/2025-23092/ensuring-a-national-policy-framework-for-artificial-intelligence">https://www.federalregister.gov/documents/2025/12/16/2025-23092/ensuring-a-national-policy-framework-for-artificial-intelligence</a>.
</div>
<div id="ref-EO14179" class="csl-entry" role="listitem">
Executive Office of the President. 2025b. <span>“Removing Barriers to American Leadership in Artificial Intelligence.”</span> In <em>Federal Register</em>, Executive Order 14179, vol. 90. <a href="https://www.federalregister.gov/documents/2025/01/31/2025-02172/removing-barriers-to-american-leadership-in-artificial-intelligence">https://www.federalregister.gov/documents/2025/01/31/2025-02172/removing-barriers-to-american-leadership-in-artificial-intelligence</a>.
</div>
<div id="ref-FTC2024-operationai" class="csl-entry" role="listitem">
Federal Trade Commission. 2024. <em><span>FTC</span> Announces Crackdown on Deceptive <span>AI</span> Claims and Schemes</em>. <a href="https://www.ftc.gov/news-events/news/press-releases/2024/09/ftc-announces-crackdown-deceptive-ai-claims-schemes">https://www.ftc.gov/news-events/news/press-releases/2024/09/ftc-announces-crackdown-deceptive-ai-claims-schemes</a>.
</div>
<div id="ref-ColoradoHB26-1139" class="csl-entry" role="listitem">
<span>HB 26-1139</span>: Use of Artificial Intelligence in Health Care (2026). <a href="https://leg.colorado.gov/bills/hb26-1139">https://leg.colorado.gov/bills/hb26-1139</a>.
</div>
<div id="ref-ISO2023-42001" class="csl-entry" role="listitem">
<span>ISO/IEC 42001</span>: Information Technology — Artificial Intelligence — Management System (2023). <a href="https://www.iso.org/standard/81230.html">https://www.iso.org/standard/81230.html</a>.
</div>
<div id="ref-NYCLL144" class="csl-entry" role="listitem">
Local Law 144: Automated Employment Decision Tools (2021). <a href="https://www.nyc.gov/site/dca/about/automated-employment-decision-tools.page">https://www.nyc.gov/site/dca/about/automated-employment-decision-tools.page</a>.
</div>
<div id="ref-NIST2023-airm" class="csl-entry" role="listitem">
National Institute of Standards and Technology. 2023. <em>Artificial Intelligence Risk Management Framework (<span>AI RMF</span> 1.0)</em>. NIST AI 100-1. U.S. Department of Commerce. <a href="https://doi.org/10.6028/NIST.AI.100-1">https://doi.org/10.6028/NIST.AI.100-1</a>.
</div>
<div id="ref-NIST2024-gen600" class="csl-entry" role="listitem">
National Institute of Standards and Technology. 2024. <em>Artificial Intelligence Risk Management Framework: Generative Artificial Intelligence Profile</em>. NIST AI 600-1. U.S. Department of Commerce. <a href="https://doi.org/10.6028/NIST.AI.600-1">https://doi.org/10.6028/NIST.AI.600-1</a>.
</div>
<div id="ref-TexasAG2024-pieces" class="csl-entry" role="listitem">
Office of the Attorney General of Texas. 2024. <em>Attorney General <span>Ken Paxton</span> Reaches Settlement in First-of-Its-Kind Healthcare Generative <span>AI</span> Investigation</em>. <a href="https://www.texasattorneygeneral.gov/news/releases/attorney-general-ken-paxton-reaches-settlement-first-its-kind-healthcare-generative-ai-investigation">https://www.texasattorneygeneral.gov/news/releases/attorney-general-ken-paxton-reaches-settlement-first-its-kind-healthcare-generative-ai-investigation</a>.
</div>
<div id="ref-CFR422101" class="csl-entry" role="listitem">
Office of the Federal Register. 2026. <em>42 <span>CFR</span> 422.101: Requirements Relating to Basic Benefits</em>. <a href="https://www.ecfr.gov/current/title-42/chapter-IV/subchapter-B/part-422/subpart-C/section-422.101">https://www.ecfr.gov/current/title-42/chapter-IV/subchapter-B/part-422/subpart-C/section-422.101</a>.
</div>
<div id="ref-ONC2024-hti1" class="csl-entry" role="listitem">
Office of the National Coordinator for Health Information Technology. 2024. <span>“Health Data, Technology, and Interoperability: Certification Program Updates, Algorithm Transparency, and Information Sharing (<span>HTI-1</span>).”</span> In <em>Federal Register</em>, No. 8, vol. 89. <a href="https://www.federalregister.gov/documents/2024/01/09/2023-28824/health-data-technology-and-interoperability-certification-program-updates-algorithm-transparency-and">https://www.federalregister.gov/documents/2024/01/09/2023-28824/health-data-technology-and-interoperability-certification-program-updates-algorithm-transparency-and</a>.
</div>
<div id="ref-EUAI2024" class="csl-entry" role="listitem">
Regulation (<span>EU</span>) 2024/1689 of the European Parliament and of the Council on Artificial Intelligence (Artificial Intelligence Act) (2024). <a href="https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=OJ:L_202401689">https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=OJ:L_202401689</a>.
</div>
<div id="ref-EUOmnibus2026" class="csl-entry" role="listitem">
Regulation (<span>EU</span>) 2026/1744 of the European Parliament and of the Council of 8 July 2026 Amending Regulations (<span>EU</span>) 2024/1689, (<span>EU</span>) 2018/1139 and (<span>EU</span>) 2023/1230 as Regards the Simplification of the Implementation of Harmonised Rules on Artificial Intelligence (Digital Omnibus on <span>AI</span>) (2026). <a href="https://eur-lex.europa.eu/eli/reg/2026/1744/oj">https://eur-lex.europa.eu/eli/reg/2026/1744/oj</a>.
</div>
<div id="ref-ColoradoSB24205" class="csl-entry" role="listitem">
<span>SB 24-205</span>: Consumer Protections for Artificial Intelligence (2024). <a href="https://leg.colorado.gov/bills/sb24-205">https://leg.colorado.gov/bills/sb24-205</a>.
</div>
<div id="ref-ColoradoSB25B004" class="csl-entry" role="listitem">
<span>SB 25B-004</span>: Increase Transparency for Algorithmic Systems (2025). <a href="https://leg.colorado.gov/bills/sb25b-004">https://leg.colorado.gov/bills/sb25b-004</a>.
</div>
<div id="ref-ColoradoSB26189" class="csl-entry" role="listitem">
<span>SB 26-189</span>: Automated Decision-Making Technology (2026). <a href="https://leg.colorado.gov/bills/sb26-189">https://leg.colorado.gov/bills/sb26-189</a>.
</div>
<div id="ref-HHS2024-1557" class="csl-entry" role="listitem">
U.S. Department of Health and Human Services, Office for Civil Rights. 2024. <span>“Nondiscrimination in Health Programs and Activities (Final Rule).”</span> In <em>Federal Register</em>, vol. 89. <a href="https://www.federalregister.gov/documents/2024/05/06/2024-08711/nondiscrimination-in-health-programs-and-activities">https://www.federalregister.gov/documents/2024/05/06/2024-08711/nondiscrimination-in-health-programs-and-activities</a>.
</div>
<div id="ref-XAI2026-weiser" class="csl-entry" role="listitem">
U.S. District Court for the District of Colorado. 2026. <em><span class="nocase">X.AI LLC v. Weiser</span>, No. 1:26-Cv-01515 (<span>D</span>. <span>C</span>olo.)</em>. <a href="https://clearinghouse.net/case/48129/">https://clearinghouse.net/case/48129/</a>.
</div>
<div id="ref-FDA2024-pccp" class="csl-entry" role="listitem">
U.S. Food and Drug Administration. 2024. <em>Marketing Submission Recommendations for a Predetermined Change Control Plan for <span>Artificial Intelligence</span>-Enabled Device Software Functions</em>. <a href="https://www.fda.gov/regulatory-information/search-fda-guidance-documents/marketing-submission-recommendations-predetermined-change-control-plan-artificial-intelligence">https://www.fda.gov/regulatory-information/search-fda-guidance-documents/marketing-submission-recommendations-predetermined-change-control-plan-artificial-intelligence</a>.
</div>
<div id="ref-FDA2026-cds" class="csl-entry" role="listitem">
U.S. Food and Drug Administration. 2026. <em>Clinical Decision Support Software: Guidance for Industry and Food and Drug Administration Staff</em>. FDA-2017-D-6569. <a href="https://www.fda.gov/regulatory-information/search-fda-guidance-documents/clinical-decision-support-software">https://www.fda.gov/regulatory-information/search-fda-guidance-documents/clinical-decision-support-software</a>.
</div>
</div>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/seandavi\.github\.io\/amc-ai-governance\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./resources_business.html" class="pagination-link" aria-label="Business Operations">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Business Operations</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./agentic_safety.html" class="pagination-link" aria-label="Agentic Safety and Guardrails">
        <span class="nav-page-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Agentic Safety and Guardrails</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">

<div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/seandavi/amc-ai-governance/edit/main/regulatory_landscape.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li></ul></div><div class="cookie-consent-footer"><a href="#" id="open_preferences_center">Cookie Preferences</a></div></div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




<script src="site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>